### ISSUE TITLE
Unexpected token < in node_modules

### ISSUE THREAD

**Issue by ImLoaD** [michaelpwilson/sails-angular2-starter#1]
Hi! I cloned this project with Git ang install packages with npm intstall. After this i run "sails lift" or "npm start" ang get that's error: 
SyntaxError: /home/xde/www/sails-angular2-starter/node_modules/angular2/ts/package.json: Unexpected token <

**Comment by michaelpwilson** [comment]
Hi, thanks for raising a ticket, I never spotted this issue before...

I've put a fix in place which now prevents this error.

**Comment by ImLoaD** [comment]
Thank you. I fix it by delete node_modules/angular2/ts folder. It's work for me
